from tkinter import *
win=Tk()
win.titile('mypython')
win.minsize(300,300)
b3=Button(win,text="python")
b1=Button(win,text="java")
b2=Button(win,text="oracle")
b4=Button(win,text="c++")
b1.pack(side=LEFT)
b2.pack(side=RIGHT)
b3.pack(side=TOP)
b4.pack(side=BOTTOM)
win.mainloop()
top=Tk()
b=Button(top,text="simple")
b.pack()
top.mainloop()
