from  tkinter import *
window=Tk()
window1=Tk()
window.configure(bg='red')
window1.configure(bg='yellow')
b1=Button(window,text="RED",bg='blue')
b2=Button(window,text="YELLOW",bg='green')
b1.pack()
b2.pack()
window.title('hello python')
window1.title('hello python')
window.geometry("300x200+400+30")
window1.geometry("300x200+400+30")
window.mainloop()